### PR TITLE
Build Windows Wheels

### LINKED ISSUE #141: Create wheels
This is a ticket to chat about improving installation -

Originally I was going to suggest a manylinux WHL.. but I'm not convinced this is as possible, after having a bit of a play with trying to do this with pycairo.

The problem with using manylinux, is that cairo compiled with the standard options pulls in too many dependencies, since all backends are enabled.

My current thinking is that going to cairo itself and working out how to split up the backends could be an interesting option.

### PR DESCRIPTION
**Pull request by naveen521kk**
Fixes #141 
Builds a wheel installable all over python3 and not specific to python version but specific to platform version. The wheel generated by Github Actions can be installed in any python version(v3) but specific to whether it is x86 or x64. 

Thanks to https://github.com/preshing/cairo-windows for created compiled cairo dlls. 
Also, inspiration taken from 
- https://www.lfd.uci.edu/~gohlke/pythonlibs/#cairocffi

It works on my PC.(Windows 10 x64)

### CODE REVIEW

**Comment by naveen521kk** [comment]
Also, fixes https://github.com/Kozea/CairoSVG/issues/279

**Comment by naveen521kk** [comment]
Any idea's will this be merged?

**Comment by liZe** [comment]
> Any idea's will this be merged?

It could be. Why did you close the PR?

**Comment by naveen521kk** [comment]
I had to close this because I really had to go(will not be available till next year) and if any changes requested I wouldn't be able to do it.
 I am reopening it. Anyhow, I would be able to come around here though.

**Comment by naveen521kk** [comment]
Can this be merged?

**Pull request closed without merging**
