### PR TITLE
Update context.py

### PR DESCRIPTION
**Pull request by williamgeraldo**
Type hint for the correct understanding of types by modern editors like vscode and similar

### CODE REVIEW

**Comment by liZe** [comment]
Hi!

Thanks for your pull request.

We don’t like Python typing annotations very much, that’s why we don’t have them and we won’t add them.

**Comment by williamgeraldo** [comment]
Understanding, however some code analyzers are generating an error. an example is the parameter `alpha=0` which is identified as an integer and the correct one is float

**Comment by williamgeraldo** [comment]
.

**Comment by liZe** [comment]
> Understanding, however some code analyzers are generating an error. an example is the parameter `alpha=0` which is identified as an integer and the correct one is float

If the code analyzer is wrong, then the bug should be reported on their bug tracker. 😄

More seriously, code analyzers can’t find solid information without manual typing annotations, maybe it’s useless to use one with cairocffi. We think that tools are supposed to help us in our work, not that we have to work to help tools to work correctly. We love Python’s dynamic typing because it gives the possibility to write code without thinking about types. We also find the code more readable.

It doesn’t mean that type annotations are bad, it just means that we prefer to code without them.

If you really want to have type hints for cairocffi, another possibility is to add cairocffi to [typeshed](https://github.com/python/typeshed/tree/main/stubs).

**Pull request closed without merging**
