### PR TITLE
added fallback ffi dload

### PR DESCRIPTION
**Pull request by cinatic**
this will help in case ctypes.util find_libary is not working (e.g. in alpine 3.x)

see also
[docker-library/python#111 (comment)](https://github.com/docker-library/python/issues/111#issuecomment-437625964)
[#699 (comment)](https://github.com/Kozea/WeasyPrint/issues/699#issuecomment-455180488)
https://github.com/Kozea/WeasyPrint/pull/784

### CODE REVIEW

**Comment by liZe** [comment]
Wow, I've just tried another (more violent) solution in 509af10. Does it work for you?

**Comment by cinatic** [comment]
yes i did a quick test it works as good as my change, thanks for the update

**Comment by cinatic** [comment]
actually it does not work, i think this 

`lib = ffi.dlopen(path or name)`

was meant to be 

`lib = ffi.dlopen(path or lib_name)`

**Comment by liZe** [comment]
> yes i did a quick test it works as good as my change, thanks for the update

Thanks a lot for the quick answer.

> actually it does not work, i think this
> 
> `lib = ffi.dlopen(path or name)`
> 
> was meant to be
> 
> `lib = ffi.dlopen(path or lib_name)`

Of course!

**Comment by Tontyna** [comment]
@liZe I suggest to not call `find_library` at all -- afaik `ffi.dlopen()` calls it anyway (unless the given `name` contains **dots** or slashes, then it tries to `load_library` first) -- cf. `dlopen()` in [weasyprint.text](https://github.com/Kozea/WeasyPrint/blob/8d10c011d9d5f6bcd474d76feadf3c1832f87d48/weasyprint/text.py)
That is to say, I don't believe this workaround is a workaround for libraries without soname and a dot-less searchname. IMHO it's the added **'cairo.so.2** that saved the day for @cinatic.

BTW: I'm wondering why **cairo-gobject-2** is in the search name list for the cairo library. Isn't cairo-gobject a helper library providing GObject bindings for cairo?

**Comment by liZe** [comment]
> That is to say, I don't believe this workaround is a workaround for libraries without soname and a dot-less searchname. IMHO it's the added **'cairo.so.2** that saved the day for @cinatic.

You're right, we should probably use WeasyPrint's `dlopen` function (and see if anyone complains).

> BTW: I'm wondering why **cairo-gobject-2** is in the search name list for the cairo library. Isn't cairo-gobject a helper library providing GObject bindings for cairo?

It was added by #112, and as it was harmless I had merged it. But again you're right, it's probably useless. @RedBug312 uses "might" in #112, so we can assume that it actually never helped anyone.

**Comment by liZe** [comment]
See #63 and #69 too about `load_library`.

**Comment by liZe** [comment]
I've open #135, but we should add CI for Windows and Mac before merging.

**Comment by Tontyna** [comment]
> It was added by #112, and as it was harmless.

It is harmless as long as loading `cairo-gobject-2` only succeeds when it opens a library with an interface that fulfills our `cairo.cdef`
Which, of course, is true for all given library search names. Reminds me of css font stacks. Though an ugly font stack doesnt crash the browser...

Main and unsolvable problem when loading a library is that `ctypes.util.find_library()` and `ctypes.CDLL()` use different algorithms to detect the requested library. 
Not talking about the fact how complicated and sometimes impossible it is on Linux to retrieve the `soname`, OMG! calling a compiler, catching and grepping its output to get a filename, that's beyond me...
Not talking about the fact that `find_library` on Linux (intentionally) doesn't return a full path.

`CDLL()` uses `LoadLibrary` on Windows, on Posix `dlopen` is called. If you compare the docs of those OS funtions with the pythonic implementation of `find_library` you can't but count yourself lucky each time `ffi.dlopen()` indeed opened exactly the library you wanted...

**Comment by RedBug312** [comment]
> @RedBug312 uses "might" in #112, so we can assume that it actually never helped anyone.

Sorry that I've misused the word. In my [side project](https://github.com/RedBug312/midi-visualizer#windows), `cairo-gobject-2` *has to* be appended to support PyGObject for Windows. It names its dll library `libcairo-gobject-2.dll`, thus `ctypes.util.find_library` and `cffi.FFI().dlopen` has to search by the name `libcairo-gobject-2`.

cairo

> calling a compiler, catching and grepping its output to get a filename

[`find_library`](https://docs.python.org/2/library/ctypes.html#finding-shared-libraries) can fetch library filepath by searching library caches (ldconfig). I think calling linker (gcc) or scanned compiled files (objdump) are just fallback approaches.

Btw, `ffi.dlopen` doc [said](https://cffi.readthedocs.io/en/latest/overview.html?highlight=dlopen#out-of-line-abi-level) default in-line mode already handles magics like prepending `lib` or appending `.so`. Then `'libcairo.so'` is not required if `'cairo'` has been checked.

**Comment by Tontyna** [comment]
>  `find_library` fetches library filename by searching library caches (ldconfig). I think calling linker (gcc) or scanned compiled files (objdump) are just fallback approaches.

Afaik, on Windows `find_library` only checks Python's `os.environment['PATH'}`.
Afaik, on Windows, `find_library` only appends `.dll` to the given search name. `lib`, `.so` and `.dylib` magics only happens on posix OS.

Are you sure that PyGObject doesnt follow this pattern?

Of course, if PyGObject's **cairo** library is named `libcairo-gobject-2`, this search name is required.

**Comment by Tontyna** [comment]
The [PyGObject docs](https://pygobject.readthedocs.io/en/latest/guide/cairo_integration.html) state:

> Note that PyGObject currently does not support cairocffi, only pycairo.

I'm almost sure that the `libcairo-gobject-2.dll` in your site-packages\gnome folder is **not** the cairo DLL that cairocffi requires. Indeed I believe it's not a **Cairo** library at all but, as the name says: a libraray that provides gobject bindings for cairo.

**Comment by Tontyna** [comment]
@RedBug312 Can you import and **use** `cairocffi` after it dlopened `libcairo-gobject-2.dll` as its `cairo` variable?
I mean, `cairo = ffi.dlopen()` succeeds with **any** given search name that successfully loads a dll, could be `libgraphite2` as well as `libpcre-1` -- you won't notice that on `import cairocff` but when you try to use it, e.g. 

```python
from cairocffi import cairo_version_string
print(cairo_version_string())
```

**Comment by RedBug312** [comment]
Oh I got it, it may just bypasses `dlopen`, but actually pointed to a wrong dll.

As you've mentioned, `apt` package also says `libcairo-gobject2` is just a wrapper for cairo. Through the code you gave successes and shows '1.15.2' (because it's a wrapper?).

I experiented if all the other entries of `dir(cairocffi.cairo)` exists (it remains same even if it's pointed to `curl-4`). It turns out 17 of 589 are absented if it's pointed to `libcairo-gobject-2`. Even if `libcairo-gobject2` is cairo dll, it brings compatibility problem.

Moreover, `cairocffi` has dropped support for Python < 3.5 in commit c93eb81; PyGObject for Windows only supports Python < 3.5. So it's better to remove `libcairo-gobject2` from the searching.

**Comment by Tontyna** [comment]
> the code you gave successes and shows '1.15.2' (because it's a wrapper?).

Yes. The files in the `site-packages/gnome` folder seem to be a special build (special names, minimized, optimized, patched, ...) for  PyGI/PyGObjects. 

BTW: The docs I quoted aren't relatet to the [PyGObject for Windows](https://sourceforge.net/projects/pygobjectwin32/) on SourceForge but belong to the [PyGObject](https://pypi.org/project/PyGObject/) package available on PyPI.

**Pull request closed without merging**
