### PR TITLE
on windows, libxcb is normally not available. trying to dlopen a non-…

### PR DESCRIPTION
**Pull request by bearsh**
…existent file results in an OSError

so catch that error as well as a possible import error.

### CODE REVIEW

**Comment by liZe** [comment]
Thank you!

**Comment by bearsh** [comment]
Are you interested in bundling the required dlls in the python wheel for windows?

**Comment by liZe** [comment]
> Are you interested in bundling the required dlls in the python wheel for windows?

Each time we’ve tried to improve our support of Windows for different libraries, we’ve created more problems that the ones we were supposed to fix. And we don’t even have a Windows computer at home, so… We’ll probably be quite reluctant. 😄

Adding a specific wheel for Windows means that we have to cover all versions of Windows, for all versions of Python, on all architectures, otherwise we’ll just get a lot of people complaining that the wheel is broken for them. We’ll also have macOS users asking for the same feature, of course for all the different architectures and macOS versions, and hope that Linux users will not ask to support all the distributions out there, because, you know, "I really need this library to work right now on my 7-year-old CentOS server". These wheels will have to be automatically built, tested and sent to PyPI, to avoid extra work when we release a new version. And if anything ever goes wrong because of these wheels, the solution we’ll quickly find is to ping users (ie. you) to maintain this feature, or to revert the pull request you’re about to open :smile:.

So, yes, if you’re interested in opening a pull request that does everything for us :heart:, and in maintaining this code for years, we’ll be happy to discuss the possibility to include DLLs in wheels. Otherwise, we’d prefer to keep our simple wheels and point users to the documentation when they forgot to install Cairo on their computer.

**Comment by bearsh** [comment]
I can fully understand you. And no, I don't think I'm willing to maintain this for years as I only need this pkg to be able to use https://github.com/bavovanachte/sphinx-wavedrom. Unfortunately my workmates use windows and that makes everything harder.

Maybe I'll document how to get the needed DLLs from msys2. This doc can then be linked or included in this repo or cairosvg.

**Comment by liZe** [comment]
> Maybe I'll document how to get the needed DLLs from msys2. This doc can then be linked or included in this repo or cairosvg.

You can take a look at [WeasyPrint’s documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows), it may help. We could definitely include this documentation in CairoCFFI’s documentation.

**Pull request merged**
