### PR TITLE
Automatically create a __init__.py to the _generated folder

### PR DESCRIPTION
**Pull request by BarchSteel**
This should close https://github.com/Kozea/cairocffi/issues/174

### CODE REVIEW

**Comment by liZe** [comment]
Hello @BarchSteel,

Thank you for this PR 😄.

We may take some time to merge it (or not) because of reasons explained in [this PR comment](https://github.com/Kozea/cairocffi/pull/173#issuecomment-749240431).

We’ll be back soon!

**Comment by Blarse** [comment]
ping

**Comment by Blarse** [comment]
By the way, this needs to check if __init__.py already exists, otherwise it throws an error when __init__.py is read-only.

**Comment by liZe** [comment]
Hello.

For reasons explained earlier, we really would like to avoid to change the way generated files are generated, and to avoid to add workarounds dedicated to solve third-party tools problems.

It would probably be better to report the issue to py2exe: the `__init__.py` file requirement has been dropped 10 years ago in Python 3.3, it’s probably better to solve the problem in py2exe instead of adding workarounds into all the projects that don’t provide `__init__.py` files for each module.

**Comment by liZe** [comment]
> It would probably be better to report the issue to py2exe: the `__init__.py` file requirement has been dropped 10 years ago in Python 3.3, it’s probably better to solve the problem in py2exe instead of adding workarounds into all the projects that don’t provide `__init__.py` files for each module.

It’s probably better to do this.

**Pull request closed without merging**
